name: auto restart

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次，可以根据需求调整时间
  push:
    branches:
      - release
jobs:
  auto_restart:
    runs-on: ubuntu-latest

    steps: 
      - name: Create user_info.json from environment variable
        run: echo "$USER_INFO" > user_info.json
        env:
          USER_INFO: ${{ secrets.USER_INFO}}  # 从GitHub Secrets中获取环境变量

      - name: Create env_config.json from environment variable
        run: echo "$ENV_CONFIG" > env_config.json
        env:
          ENV_CONFIG: ${{ secrets.ENV_CONFIG}}  # 从GitHub variables中获取环境变量

      - name: 运行登录脚本
        env:
          USER_INFO: ${{ secrets.USER_INFO }}
          ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
          ENV_CMD: ${{ secrets.ENV_CMD }}
        run: |
          python login_auto_deploy.py
