name: manual start

on:
  workflow_dispatch:
    inputs:
      start_type:
        description: '请选择启动方式'
        required: true
        default: 'restart'
        type: choice
        options:
          - restart
          - reset
          - keepalive
      interval:
        description: '请选择保活间隔时间(分钟)'
        required: true
        default: '20'
        type: choice
        options:
        - 0
        - 20
        - 30
        - 40
        - 50
        - 60

jobs:
  manual_restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: Create user_info.json from environment variable
        run: echo "$USER_INFO" > user_info.json
        env:
          USER_INFO: ${{ secrets.USER_INFO}}  # 从GitHub Secrets中获取环境变量

      - name: Create env_config.json from environment variable
        run: echo "$ENV_CONFIG" > env_config.json
        env:
          ENV_CONFIG: ${{ secrets.ENV_CONFIG}}  # 从GitHub variables中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 设置运行命令
        run: |
          echo "start_type: $START_TYPE"
          echo "INTERVAL: $INTERVAL"
          echo "ENV_CMD: py $START_TYPE $INTERVAL"
        env:
          INTERVAL: ${{ inputs.interval }}
          START_TYPE: ${{ inputs.start_type }}
      - name: 运行登录脚本
        env:
          USER_INFO: ${{ secrets.USER_INFO }}
          ENV_CONFIG: ${{ secrets.ENV_CONFIG }}
          ENV_CMD: py ${{ inputs.start_type }} ${{ inputs.interval }}
        run: |
          python login_auto_deploy.py